// Auto-generated interactive object library
// Contains a wide catalog of interactable props used for procedural placement

export const INTERACTIVE_OBJECTS = [
    {
        id: 'obj_001',
        name: 'Forge Crucible',
        category: 'security',
        rarity: 'common',
        energy: 0.99,
        cooldown: 18.05,
        description: 'A forge crucible patched into the frontier grids. Risk profile: high.',
        flavor: 'Forge Crucible hums with a warm tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_002',
        name: 'Diagnostic Table',
        category: 'transport',
        rarity: 'common',
        energy: 1.35,
        cooldown: 7.61,
        description: 'A diagnostic table patched into the frontier grids. Risk profile: low.',
        flavor: 'Diagnostic Table hums with a cold tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_003',
        name: 'Holo Projector',
        category: 'research',
        rarity: 'common',
        energy: 0.8,
        cooldown: 41.09,
        description: 'A holo projector patched into the frontier grids. Risk profile: high.',
        flavor: 'Holo Projector hums with a steady tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_004',
        name: 'Trade Kiosk',
        category: 'entertainment',
        rarity: 'uncommon',
        energy: 2.32,
        cooldown: 6.35,
        description: 'A trade kiosk patched into the frontier grids. Risk profile: low.',
        flavor: 'Trade Kiosk hums with a steady tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_005',
        name: 'Signal Tower',
        category: 'ancient',
        rarity: 'common',
        energy: 2.69,
        cooldown: 24.18,
        description: 'A signal tower patched into the frontier grids. Risk profile: low.',
        flavor: 'Signal Tower hums with a steady tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_006',
        name: 'Relay Beacon',
        category: 'utility',
        rarity: 'rare',
        energy: 1.81,
        cooldown: 49.58,
        description: 'A relay beacon patched into the frontier grids. Risk profile: high.',
        flavor: 'Relay Beacon hums with a steady tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_007',
        name: 'Grav Stabilizer',
        category: 'security',
        rarity: 'legendary',
        energy: 1.25,
        cooldown: 35.81,
        description: 'A grav stabilizer patched into the frontier grids. Risk profile: high.',
        flavor: 'Grav Stabilizer hums with a whispering tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage', 'siphon'],
    },
    {
        id: 'obj_008',
        name: 'Shield Emitter',
        category: 'research',
        rarity: 'common',
        energy: 0.47,
        cooldown: 41.71,
        description: 'A shield emitter patched into the frontier grids. Risk profile: medium.',
        flavor: 'Shield Emitter hums with a warm tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_009',
        name: 'Trade Kiosk',
        category: 'security',
        rarity: 'common',
        energy: 1.43,
        cooldown: 51.04,
        description: 'A trade kiosk patched into the frontier grids. Risk profile: low.',
        flavor: 'Trade Kiosk hums with a erratic tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_010',
        name: 'Sensor Mast',
        category: 'resource',
        rarity: 'uncommon',
        energy: 2.05,
        cooldown: 42.91,
        description: 'A sensor mast patched into the frontier grids. Risk profile: low.',
        flavor: 'Sensor Mast hums with a whispering tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_011',
        name: 'Forge Crucible',
        category: 'manufacturing',
        rarity: 'uncommon',
        energy: 0.91,
        cooldown: 30.96,
        description: 'A forge crucible patched into the frontier grids. Risk profile: medium.',
        flavor: 'Forge Crucible hums with a whispering tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_012',
        name: 'Trade Kiosk',
        category: 'utility',
        rarity: 'rare',
        energy: 2.24,
        cooldown: 18.37,
        description: 'A trade kiosk patched into the frontier grids. Risk profile: low.',
        flavor: 'Trade Kiosk hums with a erratic tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_013',
        name: 'Navigation Buoy',
        category: 'ancient',
        rarity: 'common',
        energy: 2.58,
        cooldown: 36.63,
        description: 'A navigation buoy patched into the frontier grids. Risk profile: high.',
        flavor: 'Navigation Buoy hums with a erratic tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_014',
        name: 'Street Console',
        category: 'entertainment',
        rarity: 'common',
        energy: 2.59,
        cooldown: 30.78,
        description: 'A street console patched into the frontier grids. Risk profile: medium.',
        flavor: 'Street Console hums with a cold tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_015',
        name: 'Scavenger Cache',
        category: 'transport',
        rarity: 'uncommon',
        energy: 2.17,
        cooldown: 29.14,
        description: 'A scavenger cache patched into the frontier grids. Risk profile: high.',
        flavor: 'Scavenger Cache hums with a steady tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_016',
        name: 'Shield Emitter',
        category: 'resource',
        rarity: 'legendary',
        energy: 0.65,
        cooldown: 32.65,
        description: 'A shield emitter patched into the frontier grids. Risk profile: low.',
        flavor: 'Shield Emitter hums with a warm tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage', 'siphon'],
    },
    {
        id: 'obj_017',
        name: 'Fuel Pump',
        category: 'manufacturing',
        rarity: 'rare',
        energy: 1.36,
        cooldown: 9.43,
        description: 'A fuel pump patched into the frontier grids. Risk profile: medium.',
        flavor: 'Fuel Pump hums with a whispering tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_018',
        name: 'Quantum Spire',
        category: 'transport',
        rarity: 'common',
        energy: 1.68,
        cooldown: 56.89,
        description: 'A quantum spire patched into the frontier grids. Risk profile: high.',
        flavor: 'Quantum Spire hums with a warm tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_019',
        name: 'Diagnostic Table',
        category: 'transport',
        rarity: 'rare',
        energy: 2.22,
        cooldown: 24.37,
        description: 'A diagnostic table patched into the frontier grids. Risk profile: medium.',
        flavor: 'Diagnostic Table hums with a steady tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_020',
        name: 'Solar Array',
        category: 'entertainment',
        rarity: 'common',
        energy: 2.11,
        cooldown: 44.86,
        description: 'A solar array patched into the frontier grids. Risk profile: high.',
        flavor: 'Solar Array hums with a cold tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_021',
        name: 'Holo Projector',
        category: 'security',
        rarity: 'epic',
        energy: 1.05,
        cooldown: 40.5,
        description: 'A holo projector patched into the frontier grids. Risk profile: high.',
        flavor: 'Holo Projector hums with a cold tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage', 'siphon'],
    },
    {
        id: 'obj_022',
        name: 'Fuel Pump',
        category: 'utility',
        rarity: 'rare',
        energy: 1.65,
        cooldown: 48.05,
        description: 'A fuel pump patched into the frontier grids. Risk profile: high.',
        flavor: 'Fuel Pump hums with a warm tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_023',
        name: 'Transit Gate',
        category: 'utility',
        rarity: 'uncommon',
        energy: 0.58,
        cooldown: 25.6,
        description: 'A transit gate patched into the frontier grids. Risk profile: medium.',
        flavor: 'Transit Gate hums with a cold tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_024',
        name: 'Loot Chest',
        category: 'resource',
        rarity: 'epic',
        energy: 2.67,
        cooldown: 10.63,
        description: 'A loot chest patched into the frontier grids. Risk profile: medium.',
        flavor: 'Loot Chest hums with a warm tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage', 'siphon'],
    },
    {
        id: 'obj_025',
        name: 'Arc Lamp',
        category: 'transport',
        rarity: 'rare',
        energy: 0.62,
        cooldown: 31.67,
        description: 'A arc lamp patched into the frontier grids. Risk profile: high.',
        flavor: 'Arc Lamp hums with a cold tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_026',
        name: 'Medic Station',
        category: 'transport',
        rarity: 'epic',
        energy: 1.36,
        cooldown: 17.44,
        description: 'A medic station patched into the frontier grids. Risk profile: high.',
        flavor: 'Medic Station hums with a cold tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage', 'siphon'],
    },
    {
        id: 'obj_027',
        name: 'Armory Locker',
        category: 'ancient',
        rarity: 'common',
        energy: 1.98,
        cooldown: 26.16,
        description: 'A armory locker patched into the frontier grids. Risk profile: high.',
        flavor: 'Armory Locker hums with a steady tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_028',
        name: 'Bio Pod',
        category: 'resource',
        rarity: 'common',
        energy: 1.15,
        cooldown: 37.77,
        description: 'A bio pod patched into the frontier grids. Risk profile: low.',
        flavor: 'Bio Pod hums with a whispering tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_029',
        name: 'Trade Kiosk',
        category: 'training',
        rarity: 'common',
        energy: 1.88,
        cooldown: 18.36,
        description: 'A trade kiosk patched into the frontier grids. Risk profile: low.',
        flavor: 'Trade Kiosk hums with a erratic tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_030',
        name: 'Refinery Valve',
        category: 'transport',
        rarity: 'common',
        energy: 1.97,
        cooldown: 17.57,
        description: 'A refinery valve patched into the frontier grids. Risk profile: low.',
        flavor: 'Refinery Valve hums with a whispering tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_031',
        name: 'Pulse Node',
        category: 'entertainment',
        rarity: 'common',
        energy: 1.48,
        cooldown: 27.98,
        description: 'A pulse node patched into the frontier grids. Risk profile: low.',
        flavor: 'Pulse Node hums with a warm tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_032',
        name: 'Reactor Console',
        category: 'decor',
        rarity: 'common',
        energy: 1.33,
        cooldown: 52.65,
        description: 'A reactor console patched into the frontier grids. Risk profile: low.',
        flavor: 'Reactor Console hums with a warm tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_033',
        name: 'Loot Chest',
        category: 'decor',
        rarity: 'rare',
        energy: 2.3,
        cooldown: 11.9,
        description: 'A loot chest patched into the frontier grids. Risk profile: low.',
        flavor: 'Loot Chest hums with a cold tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_034',
        name: 'Grav Stabilizer',
        category: 'entertainment',
        rarity: 'common',
        energy: 0.76,
        cooldown: 30.98,
        description: 'A grav stabilizer patched into the frontier grids. Risk profile: low.',
        flavor: 'Grav Stabilizer hums with a steady tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_035',
        name: 'Encrypted Cache',
        category: 'transport',
        rarity: 'common',
        energy: 1.93,
        cooldown: 35.19,
        description: 'A encrypted cache patched into the frontier grids. Risk profile: low.',
        flavor: 'Encrypted Cache hums with a warm tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_036',
        name: 'Arc Lamp',
        category: 'resource',
        rarity: 'common',
        energy: 1.51,
        cooldown: 17.54,
        description: 'A arc lamp patched into the frontier grids. Risk profile: medium.',
        flavor: 'Arc Lamp hums with a warm tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_037',
        name: 'Solar Array',
        category: 'decor',
        rarity: 'common',
        energy: 1.28,
        cooldown: 56.03,
        description: 'A solar array patched into the frontier grids. Risk profile: medium.',
        flavor: 'Solar Array hums with a erratic tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_038',
        name: 'Survey Tripod',
        category: 'transport',
        rarity: 'uncommon',
        energy: 1.52,
        cooldown: 16.25,
        description: 'A survey tripod patched into the frontier grids. Risk profile: low.',
        flavor: 'Survey Tripod hums with a warm tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_039',
        name: 'Vault Locker',
        category: 'transport',
        rarity: 'common',
        energy: 1.08,
        cooldown: 8.71,
        description: 'A vault locker patched into the frontier grids. Risk profile: medium.',
        flavor: 'Vault Locker hums with a whispering tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_040',
        name: 'Stasis Anchor',
        category: 'manufacturing',
        rarity: 'common',
        energy: 1.57,
        cooldown: 51.97,
        description: 'A stasis anchor patched into the frontier grids. Risk profile: low.',
        flavor: 'Stasis Anchor hums with a whispering tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_041',
        name: 'Refinery Valve',
        category: 'resource',
        rarity: 'uncommon',
        energy: 2.65,
        cooldown: 36.76,
        description: 'A refinery valve patched into the frontier grids. Risk profile: high.',
        flavor: 'Refinery Valve hums with a whispering tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_042',
        name: 'Supply Crate',
        category: 'research',
        rarity: 'common',
        energy: 1.94,
        cooldown: 36.52,
        description: 'A supply crate patched into the frontier grids. Risk profile: medium.',
        flavor: 'Supply Crate hums with a erratic tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_043',
        name: 'Street Console',
        category: 'utility',
        rarity: 'common',
        energy: 1.29,
        cooldown: 42.27,
        description: 'A street console patched into the frontier grids. Risk profile: medium.',
        flavor: 'Street Console hums with a steady tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_044',
        name: 'Circuit Relay',
        category: 'security',
        rarity: 'common',
        energy: 1.85,
        cooldown: 36.4,
        description: 'A circuit relay patched into the frontier grids. Risk profile: low.',
        flavor: 'Circuit Relay hums with a warm tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_045',
        name: 'Grav Stabilizer',
        category: 'resource',
        rarity: 'uncommon',
        energy: 0.63,
        cooldown: 24.85,
        description: 'A grav stabilizer patched into the frontier grids. Risk profile: low.',
        flavor: 'Grav Stabilizer hums with a cold tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_046',
        name: 'Shield Emitter',
        category: 'ancient',
        rarity: 'common',
        energy: 2.38,
        cooldown: 43.99,
        description: 'A shield emitter patched into the frontier grids. Risk profile: high.',
        flavor: 'Shield Emitter hums with a whispering tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_047',
        name: 'Data Terminal',
        category: 'transport',
        rarity: 'common',
        energy: 1.96,
        cooldown: 56.7,
        description: 'A data terminal patched into the frontier grids. Risk profile: low.',
        flavor: 'Data Terminal hums with a erratic tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_048',
        name: 'Bio Pod',
        category: 'security',
        rarity: 'rare',
        energy: 0.69,
        cooldown: 21.21,
        description: 'A bio pod patched into the frontier grids. Risk profile: low.',
        flavor: 'Bio Pod hums with a erratic tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_049',
        name: 'Street Console',
        category: 'ancient',
        rarity: 'uncommon',
        energy: 0.93,
        cooldown: 55.04,
        description: 'A street console patched into the frontier grids. Risk profile: low.',
        flavor: 'Street Console hums with a warm tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_050',
        name: 'Forge Crucible',
        category: 'decor',
        rarity: 'rare',
        energy: 0.41,
        cooldown: 24.01,
        description: 'A forge crucible patched into the frontier grids. Risk profile: low.',
        flavor: 'Forge Crucible hums with a erratic tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_051',
        name: 'Solar Array',
        category: 'entertainment',
        rarity: 'uncommon',
        energy: 1.37,
        cooldown: 6.52,
        description: 'A solar array patched into the frontier grids. Risk profile: low.',
        flavor: 'Solar Array hums with a cold tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_052',
        name: 'Grav Stabilizer',
        category: 'training',
        rarity: 'rare',
        energy: 1.76,
        cooldown: 14.0,
        description: 'A grav stabilizer patched into the frontier grids. Risk profile: low.',
        flavor: 'Grav Stabilizer hums with a warm tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_053',
        name: 'Drone Dock',
        category: 'utility',
        rarity: 'epic',
        energy: 2.29,
        cooldown: 52.48,
        description: 'A drone dock patched into the frontier grids. Risk profile: medium.',
        flavor: 'Drone Dock hums with a cold tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage', 'siphon'],
    },
    {
        id: 'obj_054',
        name: 'Diagnostic Table',
        category: 'resource',
        rarity: 'uncommon',
        energy: 1.18,
        cooldown: 36.23,
        description: 'A diagnostic table patched into the frontier grids. Risk profile: medium.',
        flavor: 'Diagnostic Table hums with a whispering tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_055',
        name: 'Refuel Pump',
        category: 'manufacturing',
        rarity: 'epic',
        energy: 0.89,
        cooldown: 14.78,
        description: 'A refuel pump patched into the frontier grids. Risk profile: low.',
        flavor: 'Refuel Pump hums with a steady tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage', 'siphon'],
    },
    {
        id: 'obj_056',
        name: 'Power Junction',
        category: 'manufacturing',
        rarity: 'rare',
        energy: 1.13,
        cooldown: 56.26,
        description: 'A power junction patched into the frontier grids. Risk profile: high.',
        flavor: 'Power Junction hums with a cold tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_057',
        name: 'Ammo Locker',
        category: 'manufacturing',
        rarity: 'rare',
        energy: 0.57,
        cooldown: 53.1,
        description: 'A ammo locker patched into the frontier grids. Risk profile: medium.',
        flavor: 'Ammo Locker hums with a cold tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_058',
        name: 'Hydroponics Tray',
        category: 'entertainment',
        rarity: 'common',
        energy: 2.35,
        cooldown: 53.05,
        description: 'A hydroponics tray patched into the frontier grids. Risk profile: low.',
        flavor: 'Hydroponics Tray hums with a warm tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_059',
        name: 'Reactor Console',
        category: 'resource',
        rarity: 'common',
        energy: 1.0,
        cooldown: 9.75,
        description: 'A reactor console patched into the frontier grids. Risk profile: medium.',
        flavor: 'Reactor Console hums with a erratic tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_060',
        name: 'Bioforge Pod',
        category: 'transport',
        rarity: 'common',
        energy: 2.75,
        cooldown: 34.96,
        description: 'A bioforge pod patched into the frontier grids. Risk profile: low.',
        flavor: 'Bioforge Pod hums with a warm tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_061',
        name: 'Medic Station',
        category: 'manufacturing',
        rarity: 'uncommon',
        energy: 2.76,
        cooldown: 8.07,
        description: 'A medic station patched into the frontier grids. Risk profile: high.',
        flavor: 'Medic Station hums with a steady tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_062',
        name: 'Sensor Mast',
        category: 'utility',
        rarity: 'uncommon',
        energy: 2.76,
        cooldown: 12.24,
        description: 'A sensor mast patched into the frontier grids. Risk profile: high.',
        flavor: 'Sensor Mast hums with a cold tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_063',
        name: 'Medic Station',
        category: 'training',
        rarity: 'rare',
        energy: 0.3,
        cooldown: 55.98,
        description: 'A medic station patched into the frontier grids. Risk profile: high.',
        flavor: 'Medic Station hums with a cold tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_064',
        name: 'Shield Emitter',
        category: 'decor',
        rarity: 'common',
        energy: 1.96,
        cooldown: 23.83,
        description: 'A shield emitter patched into the frontier grids. Risk profile: medium.',
        flavor: 'Shield Emitter hums with a warm tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_065',
        name: 'Med Drone Bay',
        category: 'ancient',
        rarity: 'uncommon',
        energy: 1.97,
        cooldown: 23.61,
        description: 'A med drone bay patched into the frontier grids. Risk profile: high.',
        flavor: 'Med Drone Bay hums with a erratic tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_066',
        name: 'Echo Beacon',
        category: 'manufacturing',
        rarity: 'common',
        energy: 1.96,
        cooldown: 26.47,
        description: 'A echo beacon patched into the frontier grids. Risk profile: high.',
        flavor: 'Echo Beacon hums with a cold tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_067',
        name: 'Cargo Pallet',
        category: 'research',
        rarity: 'common',
        energy: 1.67,
        cooldown: 6.02,
        description: 'A cargo pallet patched into the frontier grids. Risk profile: medium.',
        flavor: 'Cargo Pallet hums with a cold tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_068',
        name: 'Survey Tripod',
        category: 'research',
        rarity: 'uncommon',
        energy: 1.11,
        cooldown: 29.86,
        description: 'A survey tripod patched into the frontier grids. Risk profile: high.',
        flavor: 'Survey Tripod hums with a cold tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_069',
        name: 'Holo Projector',
        category: 'entertainment',
        rarity: 'rare',
        energy: 2.7,
        cooldown: 45.74,
        description: 'A holo projector patched into the frontier grids. Risk profile: high.',
        flavor: 'Holo Projector hums with a warm tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_070',
        name: 'Weapon Rack',
        category: 'transport',
        rarity: 'uncommon',
        energy: 1.85,
        cooldown: 11.04,
        description: 'A weapon rack patched into the frontier grids. Risk profile: low.',
        flavor: 'Weapon Rack hums with a erratic tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_071',
        name: 'Trade Kiosk',
        category: 'resource',
        rarity: 'common',
        energy: 0.42,
        cooldown: 59.13,
        description: 'A trade kiosk patched into the frontier grids. Risk profile: high.',
        flavor: 'Trade Kiosk hums with a warm tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_072',
        name: 'Quantum Spire',
        category: 'decor',
        rarity: 'epic',
        energy: 1.74,
        cooldown: 44.79,
        description: 'A quantum spire patched into the frontier grids. Risk profile: medium.',
        flavor: 'Quantum Spire hums with a steady tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage', 'siphon'],
    },
    {
        id: 'obj_073',
        name: 'Navigation Buoy',
        category: 'resource',
        rarity: 'common',
        energy: 2.02,
        cooldown: 54.2,
        description: 'A navigation buoy patched into the frontier grids. Risk profile: low.',
        flavor: 'Navigation Buoy hums with a steady tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_074',
        name: 'Trade Kiosk',
        category: 'manufacturing',
        rarity: 'rare',
        energy: 2.04,
        cooldown: 31.09,
        description: 'A trade kiosk patched into the frontier grids. Risk profile: high.',
        flavor: 'Trade Kiosk hums with a cold tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_075',
        name: 'Bio Pod',
        category: 'entertainment',
        rarity: 'common',
        energy: 1.46,
        cooldown: 34.68,
        description: 'A bio pod patched into the frontier grids. Risk profile: high.',
        flavor: 'Bio Pod hums with a whispering tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_076',
        name: 'Circuit Relay',
        category: 'entertainment',
        rarity: 'uncommon',
        energy: 2.1,
        cooldown: 33.26,
        description: 'A circuit relay patched into the frontier grids. Risk profile: high.',
        flavor: 'Circuit Relay hums with a steady tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_077',
        name: 'Solar Array',
        category: 'entertainment',
        rarity: 'uncommon',
        energy: 2.18,
        cooldown: 51.35,
        description: 'A solar array patched into the frontier grids. Risk profile: medium.',
        flavor: 'Solar Array hums with a whispering tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_078',
        name: 'Memory Pillar',
        category: 'resource',
        rarity: 'common',
        energy: 0.49,
        cooldown: 21.43,
        description: 'A memory pillar patched into the frontier grids. Risk profile: medium.',
        flavor: 'Memory Pillar hums with a erratic tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_079',
        name: 'Circuit Relay',
        category: 'transport',
        rarity: 'common',
        energy: 0.68,
        cooldown: 26.68,
        description: 'A circuit relay patched into the frontier grids. Risk profile: low.',
        flavor: 'Circuit Relay hums with a cold tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_080',
        name: 'Refinery Valve',
        category: 'decor',
        rarity: 'uncommon',
        energy: 1.66,
        cooldown: 28.45,
        description: 'A refinery valve patched into the frontier grids. Risk profile: low.',
        flavor: 'Refinery Valve hums with a steady tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_081',
        name: 'Generator Core',
        category: 'research',
        rarity: 'epic',
        energy: 0.35,
        cooldown: 53.56,
        description: 'A generator core patched into the frontier grids. Risk profile: high.',
        flavor: 'Generator Core hums with a steady tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage', 'siphon'],
    },
    {
        id: 'obj_082',
        name: 'Atlas Monolith',
        category: 'training',
        rarity: 'epic',
        energy: 1.05,
        cooldown: 27.06,
        description: 'A atlas monolith patched into the frontier grids. Risk profile: medium.',
        flavor: 'Atlas Monolith hums with a whispering tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage', 'siphon'],
    },
    {
        id: 'obj_083',
        name: 'Refuel Pump',
        category: 'transport',
        rarity: 'rare',
        energy: 2.54,
        cooldown: 32.36,
        description: 'A refuel pump patched into the frontier grids. Risk profile: medium.',
        flavor: 'Refuel Pump hums with a steady tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_084',
        name: 'Memory Pillar',
        category: 'training',
        rarity: 'common',
        energy: 1.97,
        cooldown: 49.1,
        description: 'A memory pillar patched into the frontier grids. Risk profile: high.',
        flavor: 'Memory Pillar hums with a cold tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_085',
        name: 'Quantum Spire',
        category: 'manufacturing',
        rarity: 'legendary',
        energy: 1.64,
        cooldown: 54.97,
        description: 'A quantum spire patched into the frontier grids. Risk profile: high.',
        flavor: 'Quantum Spire hums with a whispering tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage', 'siphon'],
    },
    {
        id: 'obj_086',
        name: 'Reactor Console',
        category: 'training',
        rarity: 'common',
        energy: 1.37,
        cooldown: 52.81,
        description: 'A reactor console patched into the frontier grids. Risk profile: low.',
        flavor: 'Reactor Console hums with a warm tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_087',
        name: 'Medic Station',
        category: 'decor',
        rarity: 'common',
        energy: 1.44,
        cooldown: 24.23,
        description: 'A medic station patched into the frontier grids. Risk profile: medium.',
        flavor: 'Medic Station hums with a erratic tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_088',
        name: 'Arc Lamp',
        category: 'decor',
        rarity: 'common',
        energy: 0.5,
        cooldown: 7.05,
        description: 'A arc lamp patched into the frontier grids. Risk profile: high.',
        flavor: 'Arc Lamp hums with a warm tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_089',
        name: 'Sensor Mast',
        category: 'resource',
        rarity: 'uncommon',
        energy: 2.25,
        cooldown: 41.19,
        description: 'A sensor mast patched into the frontier grids. Risk profile: low.',
        flavor: 'Sensor Mast hums with a cold tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_090',
        name: 'Hydroponics Tray',
        category: 'training',
        rarity: 'uncommon',
        energy: 0.9,
        cooldown: 31.57,
        description: 'A hydroponics tray patched into the frontier grids. Risk profile: low.',
        flavor: 'Hydroponics Tray hums with a whispering tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_091',
        name: 'Street Console',
        category: 'entertainment',
        rarity: 'uncommon',
        energy: 2.22,
        cooldown: 15.06,
        description: 'A street console patched into the frontier grids. Risk profile: high.',
        flavor: 'Street Console hums with a warm tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_092',
        name: 'Hydro Tap',
        category: 'manufacturing',
        rarity: 'legendary',
        energy: 0.57,
        cooldown: 7.39,
        description: 'A hydro tap patched into the frontier grids. Risk profile: medium.',
        flavor: 'Hydro Tap hums with a whispering tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage', 'siphon'],
    },
    {
        id: 'obj_093',
        name: 'Diagnostic Table',
        category: 'decor',
        rarity: 'common',
        energy: 2.09,
        cooldown: 10.1,
        description: 'A diagnostic table patched into the frontier grids. Risk profile: high.',
        flavor: 'Diagnostic Table hums with a cold tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_094',
        name: 'Relay Beacon',
        category: 'ancient',
        rarity: 'epic',
        energy: 1.8,
        cooldown: 12.54,
        description: 'A relay beacon patched into the frontier grids. Risk profile: high.',
        flavor: 'Relay Beacon hums with a warm tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage', 'siphon'],
    },
    {
        id: 'obj_095',
        name: 'Sensor Mast',
        category: 'transport',
        rarity: 'uncommon',
        energy: 1.23,
        cooldown: 33.32,
        description: 'A sensor mast patched into the frontier grids. Risk profile: medium.',
        flavor: 'Sensor Mast hums with a warm tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_096',
        name: 'Weather Node',
        category: 'entertainment',
        rarity: 'common',
        energy: 2.7,
        cooldown: 40.32,
        description: 'A weather node patched into the frontier grids. Risk profile: medium.',
        flavor: 'Weather Node hums with a cold tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_097',
        name: 'Survey Tripod',
        category: 'manufacturing',
        rarity: 'rare',
        energy: 2.71,
        cooldown: 20.58,
        description: 'A survey tripod patched into the frontier grids. Risk profile: high.',
        flavor: 'Survey Tripod hums with a steady tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_098',
        name: 'Quantum Spire',
        category: 'decor',
        rarity: 'rare',
        energy: 1.78,
        cooldown: 23.4,
        description: 'A quantum spire patched into the frontier grids. Risk profile: low.',
        flavor: 'Quantum Spire hums with a warm tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_099',
        name: 'Ammo Locker',
        category: 'entertainment',
        rarity: 'common',
        energy: 1.46,
        cooldown: 38.96,
        description: 'A ammo locker patched into the frontier grids. Risk profile: medium.',
        flavor: 'Ammo Locker hums with a erratic tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_100',
        name: 'Power Junction',
        category: 'entertainment',
        rarity: 'epic',
        energy: 0.75,
        cooldown: 17.45,
        description: 'A power junction patched into the frontier grids. Risk profile: medium.',
        flavor: 'Power Junction hums with a erratic tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage', 'siphon'],
    },
    {
        id: 'obj_101',
        name: 'Ammo Locker',
        category: 'research',
        rarity: 'rare',
        energy: 0.99,
        cooldown: 6.55,
        description: 'A ammo locker patched into the frontier grids. Risk profile: low.',
        flavor: 'Ammo Locker hums with a warm tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_102',
        name: 'Scavenger Cache',
        category: 'decor',
        rarity: 'uncommon',
        energy: 2.2,
        cooldown: 43.29,
        description: 'A scavenger cache patched into the frontier grids. Risk profile: high.',
        flavor: 'Scavenger Cache hums with a steady tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_103',
        name: 'Comms Uplink',
        category: 'training',
        rarity: 'common',
        energy: 0.85,
        cooldown: 43.36,
        description: 'A comms uplink patched into the frontier grids. Risk profile: medium.',
        flavor: 'Comms Uplink hums with a whispering tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_104',
        name: 'Shield Emitter',
        category: 'entertainment',
        rarity: 'uncommon',
        energy: 1.16,
        cooldown: 59.82,
        description: 'A shield emitter patched into the frontier grids. Risk profile: high.',
        flavor: 'Shield Emitter hums with a erratic tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_105',
        name: 'Sensor Mast',
        category: 'entertainment',
        rarity: 'common',
        energy: 0.93,
        cooldown: 12.52,
        description: 'A sensor mast patched into the frontier grids. Risk profile: low.',
        flavor: 'Sensor Mast hums with a erratic tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_106',
        name: 'Bio Pod',
        category: 'transport',
        rarity: 'legendary',
        energy: 2.03,
        cooldown: 16.34,
        description: 'A bio pod patched into the frontier grids. Risk profile: high.',
        flavor: 'Bio Pod hums with a steady tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage', 'siphon'],
    },
    {
        id: 'obj_107',
        name: 'Ammo Locker',
        category: 'research',
        rarity: 'legendary',
        energy: 1.61,
        cooldown: 21.28,
        description: 'A ammo locker patched into the frontier grids. Risk profile: low.',
        flavor: 'Ammo Locker hums with a cold tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage', 'siphon'],
    },
    {
        id: 'obj_108',
        name: 'Weapon Rack',
        category: 'resource',
        rarity: 'common',
        energy: 1.06,
        cooldown: 44.23,
        description: 'A weapon rack patched into the frontier grids. Risk profile: low.',
        flavor: 'Weapon Rack hums with a erratic tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_109',
        name: 'Supply Crate',
        category: 'training',
        rarity: 'uncommon',
        energy: 2.04,
        cooldown: 12.82,
        description: 'A supply crate patched into the frontier grids. Risk profile: medium.',
        flavor: 'Supply Crate hums with a warm tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_110',
        name: 'Data Terminal',
        category: 'research',
        rarity: 'common',
        energy: 1.5,
        cooldown: 24.4,
        description: 'A data terminal patched into the frontier grids. Risk profile: low.',
        flavor: 'Data Terminal hums with a erratic tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_111',
        name: 'Atlas Monolith',
        category: 'security',
        rarity: 'rare',
        energy: 1.3,
        cooldown: 10.0,
        description: 'A atlas monolith patched into the frontier grids. Risk profile: high.',
        flavor: 'Atlas Monolith hums with a warm tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_112',
        name: 'Fuel Pump',
        category: 'manufacturing',
        rarity: 'rare',
        energy: 2.67,
        cooldown: 10.6,
        description: 'A fuel pump patched into the frontier grids. Risk profile: low.',
        flavor: 'Fuel Pump hums with a warm tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_113',
        name: 'Echo Beacon',
        category: 'decor',
        rarity: 'uncommon',
        energy: 2.28,
        cooldown: 18.19,
        description: 'A echo beacon patched into the frontier grids. Risk profile: high.',
        flavor: 'Echo Beacon hums with a steady tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_114',
        name: 'Comms Uplink',
        category: 'entertainment',
        rarity: 'common',
        energy: 1.77,
        cooldown: 29.16,
        description: 'A comms uplink patched into the frontier grids. Risk profile: high.',
        flavor: 'Comms Uplink hums with a whispering tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_115',
        name: 'Loot Chest',
        category: 'research',
        rarity: 'legendary',
        energy: 0.55,
        cooldown: 47.19,
        description: 'A loot chest patched into the frontier grids. Risk profile: high.',
        flavor: 'Loot Chest hums with a cold tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage', 'siphon'],
    },
    {
        id: 'obj_116',
        name: 'Medic Station',
        category: 'security',
        rarity: 'common',
        energy: 0.73,
        cooldown: 10.05,
        description: 'A medic station patched into the frontier grids. Risk profile: low.',
        flavor: 'Medic Station hums with a steady tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_117',
        name: 'Comms Uplink',
        category: 'research',
        rarity: 'uncommon',
        energy: 0.38,
        cooldown: 21.56,
        description: 'A comms uplink patched into the frontier grids. Risk profile: medium.',
        flavor: 'Comms Uplink hums with a steady tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_118',
        name: 'Refinery Valve',
        category: 'resource',
        rarity: 'epic',
        energy: 2.27,
        cooldown: 39.75,
        description: 'A refinery valve patched into the frontier grids. Risk profile: high.',
        flavor: 'Refinery Valve hums with a cold tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage', 'siphon'],
    },
    {
        id: 'obj_119',
        name: 'Survey Tripod',
        category: 'security',
        rarity: 'uncommon',
        energy: 1.92,
        cooldown: 55.05,
        description: 'A survey tripod patched into the frontier grids. Risk profile: low.',
        flavor: 'Survey Tripod hums with a warm tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_120',
        name: 'Loot Chest',
        category: 'manufacturing',
        rarity: 'rare',
        energy: 1.79,
        cooldown: 50.51,
        description: 'A loot chest patched into the frontier grids. Risk profile: medium.',
        flavor: 'Loot Chest hums with a steady tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_121',
        name: 'Bio Pod',
        category: 'entertainment',
        rarity: 'uncommon',
        energy: 2.05,
        cooldown: 56.9,
        description: 'A bio pod patched into the frontier grids. Risk profile: high.',
        flavor: 'Bio Pod hums with a whispering tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_122',
        name: 'Memory Pillar',
        category: 'entertainment',
        rarity: 'common',
        energy: 0.4,
        cooldown: 29.33,
        description: 'A memory pillar patched into the frontier grids. Risk profile: medium.',
        flavor: 'Memory Pillar hums with a whispering tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_123',
        name: 'Medic Station',
        category: 'training',
        rarity: 'common',
        energy: 2.7,
        cooldown: 51.14,
        description: 'A medic station patched into the frontier grids. Risk profile: high.',
        flavor: 'Medic Station hums with a whispering tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_124',
        name: 'Power Junction',
        category: 'ancient',
        rarity: 'uncommon',
        energy: 2.21,
        cooldown: 15.46,
        description: 'A power junction patched into the frontier grids. Risk profile: high.',
        flavor: 'Power Junction hums with a steady tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_125',
        name: 'Ammo Locker',
        category: 'manufacturing',
        rarity: 'legendary',
        energy: 1.39,
        cooldown: 49.97,
        description: 'A ammo locker patched into the frontier grids. Risk profile: low.',
        flavor: 'Ammo Locker hums with a steady tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage', 'siphon'],
    },
    {
        id: 'obj_126',
        name: 'Sensor Mast',
        category: 'decor',
        rarity: 'common',
        energy: 1.98,
        cooldown: 52.32,
        description: 'A sensor mast patched into the frontier grids. Risk profile: medium.',
        flavor: 'Sensor Mast hums with a steady tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_127',
        name: 'Security Kiosk',
        category: 'entertainment',
        rarity: 'common',
        energy: 2.66,
        cooldown: 49.93,
        description: 'A security kiosk patched into the frontier grids. Risk profile: high.',
        flavor: 'Security Kiosk hums with a warm tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_128',
        name: 'Quantum Spire',
        category: 'security',
        rarity: 'common',
        energy: 1.11,
        cooldown: 58.39,
        description: 'A quantum spire patched into the frontier grids. Risk profile: medium.',
        flavor: 'Quantum Spire hums with a whispering tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_129',
        name: 'Data Terminal',
        category: 'transport',
        rarity: 'uncommon',
        energy: 0.44,
        cooldown: 34.0,
        description: 'A data terminal patched into the frontier grids. Risk profile: high.',
        flavor: 'Data Terminal hums with a steady tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_130',
        name: 'Forge Crucible',
        category: 'entertainment',
        rarity: 'rare',
        energy: 0.81,
        cooldown: 35.66,
        description: 'A forge crucible patched into the frontier grids. Risk profile: medium.',
        flavor: 'Forge Crucible hums with a steady tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_131',
        name: 'Security Kiosk',
        category: 'entertainment',
        rarity: 'common',
        energy: 2.73,
        cooldown: 38.88,
        description: 'A security kiosk patched into the frontier grids. Risk profile: low.',
        flavor: 'Security Kiosk hums with a cold tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_132',
        name: 'Drone Dock',
        category: 'transport',
        rarity: 'common',
        energy: 1.32,
        cooldown: 18.13,
        description: 'A drone dock patched into the frontier grids. Risk profile: low.',
        flavor: 'Drone Dock hums with a steady tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_133',
        name: 'Bio Pod',
        category: 'manufacturing',
        rarity: 'uncommon',
        energy: 2.09,
        cooldown: 33.48,
        description: 'A bio pod patched into the frontier grids. Risk profile: medium.',
        flavor: 'Bio Pod hums with a steady tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_134',
        name: 'Atlas Monolith',
        category: 'entertainment',
        rarity: 'common',
        energy: 1.68,
        cooldown: 26.71,
        description: 'A atlas monolith patched into the frontier grids. Risk profile: high.',
        flavor: 'Atlas Monolith hums with a whispering tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_135',
        name: 'Refuel Pump',
        category: 'manufacturing',
        rarity: 'epic',
        energy: 0.99,
        cooldown: 48.66,
        description: 'A refuel pump patched into the frontier grids. Risk profile: medium.',
        flavor: 'Refuel Pump hums with a erratic tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage', 'siphon'],
    },
    {
        id: 'obj_136',
        name: 'Salvage Pile',
        category: 'transport',
        rarity: 'common',
        energy: 0.31,
        cooldown: 45.21,
        description: 'A salvage pile patched into the frontier grids. Risk profile: high.',
        flavor: 'Salvage Pile hums with a whispering tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_137',
        name: 'Reactor Console',
        category: 'entertainment',
        rarity: 'epic',
        energy: 1.42,
        cooldown: 32.15,
        description: 'A reactor console patched into the frontier grids. Risk profile: medium.',
        flavor: 'Reactor Console hums with a whispering tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage', 'siphon'],
    },
    {
        id: 'obj_138',
        name: 'Arc Lamp',
        category: 'transport',
        rarity: 'common',
        energy: 2.63,
        cooldown: 52.96,
        description: 'A arc lamp patched into the frontier grids. Risk profile: high.',
        flavor: 'Arc Lamp hums with a cold tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_139',
        name: 'Pulse Node',
        category: 'decor',
        rarity: 'common',
        energy: 2.24,
        cooldown: 8.36,
        description: 'A pulse node patched into the frontier grids. Risk profile: high.',
        flavor: 'Pulse Node hums with a steady tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_140',
        name: 'Armory Locker',
        category: 'decor',
        rarity: 'common',
        energy: 1.96,
        cooldown: 50.32,
        description: 'A armory locker patched into the frontier grids. Risk profile: low.',
        flavor: 'Armory Locker hums with a steady tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_141',
        name: 'Supply Crate',
        category: 'manufacturing',
        rarity: 'uncommon',
        energy: 1.78,
        cooldown: 52.96,
        description: 'A supply crate patched into the frontier grids. Risk profile: medium.',
        flavor: 'Supply Crate hums with a warm tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_142',
        name: 'Stasis Anchor',
        category: 'entertainment',
        rarity: 'common',
        energy: 0.66,
        cooldown: 53.03,
        description: 'A stasis anchor patched into the frontier grids. Risk profile: low.',
        flavor: 'Stasis Anchor hums with a warm tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_143',
        name: 'Atlas Monolith',
        category: 'ancient',
        rarity: 'common',
        energy: 2.03,
        cooldown: 41.09,
        description: 'A atlas monolith patched into the frontier grids. Risk profile: medium.',
        flavor: 'Atlas Monolith hums with a whispering tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_144',
        name: 'Generator Core',
        category: 'utility',
        rarity: 'uncommon',
        energy: 2.52,
        cooldown: 32.35,
        description: 'A generator core patched into the frontier grids. Risk profile: high.',
        flavor: 'Generator Core hums with a warm tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_145',
        name: 'Cargo Pallet',
        category: 'security',
        rarity: 'common',
        energy: 2.01,
        cooldown: 21.52,
        description: 'A cargo pallet patched into the frontier grids. Risk profile: low.',
        flavor: 'Cargo Pallet hums with a warm tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_146',
        name: 'Survey Tripod',
        category: 'security',
        rarity: 'rare',
        energy: 2.06,
        cooldown: 11.43,
        description: 'A survey tripod patched into the frontier grids. Risk profile: low.',
        flavor: 'Survey Tripod hums with a erratic tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_147',
        name: 'Power Junction',
        category: 'training',
        rarity: 'common',
        energy: 0.44,
        cooldown: 25.36,
        description: 'A power junction patched into the frontier grids. Risk profile: medium.',
        flavor: 'Power Junction hums with a cold tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_148',
        name: 'Scavenger Cache',
        category: 'transport',
        rarity: 'uncommon',
        energy: 2.0,
        cooldown: 15.72,
        description: 'A scavenger cache patched into the frontier grids. Risk profile: low.',
        flavor: 'Scavenger Cache hums with a warm tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_149',
        name: 'Cargo Pallet',
        category: 'decor',
        rarity: 'uncommon',
        energy: 0.9,
        cooldown: 55.29,
        description: 'A cargo pallet patched into the frontier grids. Risk profile: low.',
        flavor: 'Cargo Pallet hums with a cold tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_150',
        name: 'Quantum Spire',
        category: 'ancient',
        rarity: 'uncommon',
        energy: 1.97,
        cooldown: 54.54,
        description: 'A quantum spire patched into the frontier grids. Risk profile: medium.',
        flavor: 'Quantum Spire hums with a erratic tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_151',
        name: 'Diagnostic Table',
        category: 'transport',
        rarity: 'common',
        energy: 1.4,
        cooldown: 24.66,
        description: 'A diagnostic table patched into the frontier grids. Risk profile: high.',
        flavor: 'Diagnostic Table hums with a erratic tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_152',
        name: 'Forge Crucible',
        category: 'decor',
        rarity: 'uncommon',
        energy: 1.44,
        cooldown: 22.31,
        description: 'A forge crucible patched into the frontier grids. Risk profile: medium.',
        flavor: 'Forge Crucible hums with a steady tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_153',
        name: 'Relay Beacon',
        category: 'resource',
        rarity: 'common',
        energy: 1.2,
        cooldown: 21.98,
        description: 'A relay beacon patched into the frontier grids. Risk profile: high.',
        flavor: 'Relay Beacon hums with a erratic tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_154',
        name: 'Power Junction',
        category: 'decor',
        rarity: 'common',
        energy: 1.71,
        cooldown: 43.03,
        description: 'A power junction patched into the frontier grids. Risk profile: high.',
        flavor: 'Power Junction hums with a warm tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_155',
        name: 'Transit Gate',
        category: 'entertainment',
        rarity: 'rare',
        energy: 2.56,
        cooldown: 47.89,
        description: 'A transit gate patched into the frontier grids. Risk profile: low.',
        flavor: 'Transit Gate hums with a whispering tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_156',
        name: 'Encrypted Cache',
        category: 'utility',
        rarity: 'common',
        energy: 0.78,
        cooldown: 19.53,
        description: 'A encrypted cache patched into the frontier grids. Risk profile: high.',
        flavor: 'Encrypted Cache hums with a cold tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_157',
        name: 'Forge Crucible',
        category: 'security',
        rarity: 'epic',
        energy: 1.92,
        cooldown: 22.68,
        description: 'A forge crucible patched into the frontier grids. Risk profile: medium.',
        flavor: 'Forge Crucible hums with a warm tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage', 'siphon'],
    },
    {
        id: 'obj_158',
        name: 'Vault Locker',
        category: 'utility',
        rarity: 'rare',
        energy: 0.53,
        cooldown: 21.94,
        description: 'A vault locker patched into the frontier grids. Risk profile: high.',
        flavor: 'Vault Locker hums with a steady tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_159',
        name: 'Wind Turbine',
        category: 'resource',
        rarity: 'common',
        energy: 1.65,
        cooldown: 58.46,
        description: 'A wind turbine patched into the frontier grids. Risk profile: high.',
        flavor: 'Wind Turbine hums with a whispering tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_160',
        name: 'Ammo Locker',
        category: 'manufacturing',
        rarity: 'common',
        energy: 2.36,
        cooldown: 32.02,
        description: 'A ammo locker patched into the frontier grids. Risk profile: medium.',
        flavor: 'Ammo Locker hums with a erratic tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_161',
        name: 'Encrypted Cache',
        category: 'security',
        rarity: 'uncommon',
        energy: 0.49,
        cooldown: 46.72,
        description: 'A encrypted cache patched into the frontier grids. Risk profile: low.',
        flavor: 'Encrypted Cache hums with a steady tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_162',
        name: 'Encrypted Cache',
        category: 'transport',
        rarity: 'common',
        energy: 2.28,
        cooldown: 6.75,
        description: 'A encrypted cache patched into the frontier grids. Risk profile: high.',
        flavor: 'Encrypted Cache hums with a warm tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_163',
        name: 'Quantum Spire',
        category: 'utility',
        rarity: 'uncommon',
        energy: 1.98,
        cooldown: 37.57,
        description: 'A quantum spire patched into the frontier grids. Risk profile: high.',
        flavor: 'Quantum Spire hums with a erratic tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_164',
        name: 'Relay Beacon',
        category: 'resource',
        rarity: 'uncommon',
        energy: 1.85,
        cooldown: 56.93,
        description: 'A relay beacon patched into the frontier grids. Risk profile: medium.',
        flavor: 'Relay Beacon hums with a whispering tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_165',
        name: 'Trade Kiosk',
        category: 'security',
        rarity: 'uncommon',
        energy: 1.46,
        cooldown: 43.86,
        description: 'A trade kiosk patched into the frontier grids. Risk profile: high.',
        flavor: 'Trade Kiosk hums with a steady tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_166',
        name: 'Bio Pod',
        category: 'manufacturing',
        rarity: 'common',
        energy: 0.39,
        cooldown: 59.78,
        description: 'A bio pod patched into the frontier grids. Risk profile: low.',
        flavor: 'Bio Pod hums with a warm tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_167',
        name: 'Scavenger Cache',
        category: 'transport',
        rarity: 'common',
        energy: 1.43,
        cooldown: 42.21,
        description: 'A scavenger cache patched into the frontier grids. Risk profile: high.',
        flavor: 'Scavenger Cache hums with a whispering tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_168',
        name: 'Weather Node',
        category: 'research',
        rarity: 'rare',
        energy: 0.69,
        cooldown: 28.4,
        description: 'A weather node patched into the frontier grids. Risk profile: low.',
        flavor: 'Weather Node hums with a steady tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_169',
        name: 'Cargo Pallet',
        category: 'decor',
        rarity: 'epic',
        energy: 1.0,
        cooldown: 43.28,
        description: 'A cargo pallet patched into the frontier grids. Risk profile: low.',
        flavor: 'Cargo Pallet hums with a steady tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage', 'siphon'],
    },
    {
        id: 'obj_170',
        name: 'Comms Uplink',
        category: 'resource',
        rarity: 'epic',
        energy: 0.55,
        cooldown: 43.03,
        description: 'A comms uplink patched into the frontier grids. Risk profile: high.',
        flavor: 'Comms Uplink hums with a erratic tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage', 'siphon'],
    },
    {
        id: 'obj_171',
        name: 'Loot Chest',
        category: 'decor',
        rarity: 'common',
        energy: 2.72,
        cooldown: 57.25,
        description: 'A loot chest patched into the frontier grids. Risk profile: medium.',
        flavor: 'Loot Chest hums with a warm tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_172',
        name: 'Reactor Console',
        category: 'resource',
        rarity: 'uncommon',
        energy: 1.79,
        cooldown: 7.15,
        description: 'A reactor console patched into the frontier grids. Risk profile: medium.',
        flavor: 'Reactor Console hums with a cold tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_173',
        name: 'Cryo Tube',
        category: 'research',
        rarity: 'common',
        energy: 2.37,
        cooldown: 35.93,
        description: 'A cryo tube patched into the frontier grids. Risk profile: high.',
        flavor: 'Cryo Tube hums with a cold tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_174',
        name: 'Trade Kiosk',
        category: 'utility',
        rarity: 'rare',
        energy: 2.27,
        cooldown: 38.18,
        description: 'A trade kiosk patched into the frontier grids. Risk profile: medium.',
        flavor: 'Trade Kiosk hums with a cold tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_175',
        name: 'Cryo Tube',
        category: 'transport',
        rarity: 'common',
        energy: 0.74,
        cooldown: 41.7,
        description: 'A cryo tube patched into the frontier grids. Risk profile: low.',
        flavor: 'Cryo Tube hums with a cold tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_176',
        name: 'Data Terminal',
        category: 'utility',
        rarity: 'rare',
        energy: 0.89,
        cooldown: 23.48,
        description: 'A data terminal patched into the frontier grids. Risk profile: low.',
        flavor: 'Data Terminal hums with a erratic tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_177',
        name: 'Loot Chest',
        category: 'manufacturing',
        rarity: 'rare',
        energy: 1.62,
        cooldown: 46.27,
        description: 'A loot chest patched into the frontier grids. Risk profile: medium.',
        flavor: 'Loot Chest hums with a steady tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_178',
        name: 'Hydro Tap',
        category: 'utility',
        rarity: 'uncommon',
        energy: 0.57,
        cooldown: 33.21,
        description: 'A hydro tap patched into the frontier grids. Risk profile: high.',
        flavor: 'Hydro Tap hums with a warm tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_179',
        name: 'Med Drone Bay',
        category: 'transport',
        rarity: 'common',
        energy: 1.91,
        cooldown: 7.68,
        description: 'A med drone bay patched into the frontier grids. Risk profile: medium.',
        flavor: 'Med Drone Bay hums with a steady tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_180',
        name: 'Survey Tripod',
        category: 'security',
        rarity: 'uncommon',
        energy: 2.57,
        cooldown: 9.97,
        description: 'A survey tripod patched into the frontier grids. Risk profile: low.',
        flavor: 'Survey Tripod hums with a erratic tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_181',
        name: 'Transit Gate',
        category: 'manufacturing',
        rarity: 'common',
        energy: 0.99,
        cooldown: 40.19,
        description: 'A transit gate patched into the frontier grids. Risk profile: high.',
        flavor: 'Transit Gate hums with a erratic tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_182',
        name: 'Generator Core',
        category: 'research',
        rarity: 'uncommon',
        energy: 1.43,
        cooldown: 38.69,
        description: 'A generator core patched into the frontier grids. Risk profile: low.',
        flavor: 'Generator Core hums with a warm tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_183',
        name: 'Bioforge Pod',
        category: 'transport',
        rarity: 'rare',
        energy: 0.84,
        cooldown: 30.38,
        description: 'A bioforge pod patched into the frontier grids. Risk profile: low.',
        flavor: 'Bioforge Pod hums with a steady tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_184',
        name: 'Signal Tower',
        category: 'entertainment',
        rarity: 'common',
        energy: 2.12,
        cooldown: 22.88,
        description: 'A signal tower patched into the frontier grids. Risk profile: medium.',
        flavor: 'Signal Tower hums with a erratic tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_185',
        name: 'Shield Emitter',
        category: 'manufacturing',
        rarity: 'uncommon',
        energy: 1.49,
        cooldown: 10.93,
        description: 'A shield emitter patched into the frontier grids. Risk profile: low.',
        flavor: 'Shield Emitter hums with a warm tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_186',
        name: 'Survey Tripod',
        category: 'security',
        rarity: 'rare',
        energy: 1.23,
        cooldown: 13.03,
        description: 'A survey tripod patched into the frontier grids. Risk profile: low.',
        flavor: 'Survey Tripod hums with a whispering tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_187',
        name: 'Echo Beacon',
        category: 'transport',
        rarity: 'common',
        energy: 0.61,
        cooldown: 25.09,
        description: 'A echo beacon patched into the frontier grids. Risk profile: high.',
        flavor: 'Echo Beacon hums with a steady tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_188',
        name: 'Med Drone Bay',
        category: 'training',
        rarity: 'legendary',
        energy: 1.8,
        cooldown: 24.99,
        description: 'A med drone bay patched into the frontier grids. Risk profile: high.',
        flavor: 'Med Drone Bay hums with a whispering tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage', 'siphon'],
    },
    {
        id: 'obj_189',
        name: 'Street Console',
        category: 'manufacturing',
        rarity: 'uncommon',
        energy: 0.86,
        cooldown: 11.84,
        description: 'A street console patched into the frontier grids. Risk profile: high.',
        flavor: 'Street Console hums with a erratic tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_190',
        name: 'Bio Pod',
        category: 'ancient',
        rarity: 'uncommon',
        energy: 2.32,
        cooldown: 51.64,
        description: 'A bio pod patched into the frontier grids. Risk profile: high.',
        flavor: 'Bio Pod hums with a whispering tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_191',
        name: 'Diagnostic Table',
        category: 'transport',
        rarity: 'common',
        energy: 2.62,
        cooldown: 50.79,
        description: 'A diagnostic table patched into the frontier grids. Risk profile: medium.',
        flavor: 'Diagnostic Table hums with a warm tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_192',
        name: 'Wind Turbine',
        category: 'ancient',
        rarity: 'rare',
        energy: 1.07,
        cooldown: 24.35,
        description: 'A wind turbine patched into the frontier grids. Risk profile: low.',
        flavor: 'Wind Turbine hums with a cold tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_193',
        name: 'Fuel Pump',
        category: 'research',
        rarity: 'uncommon',
        energy: 0.47,
        cooldown: 46.01,
        description: 'A fuel pump patched into the frontier grids. Risk profile: low.',
        flavor: 'Fuel Pump hums with a warm tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_194',
        name: 'Refuel Pump',
        category: 'transport',
        rarity: 'common',
        energy: 1.35,
        cooldown: 24.41,
        description: 'A refuel pump patched into the frontier grids. Risk profile: medium.',
        flavor: 'Refuel Pump hums with a erratic tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_195',
        name: 'Med Drone Bay',
        category: 'utility',
        rarity: 'rare',
        energy: 1.72,
        cooldown: 10.59,
        description: 'A med drone bay patched into the frontier grids. Risk profile: low.',
        flavor: 'Med Drone Bay hums with a cold tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_196',
        name: 'Solar Array',
        category: 'research',
        rarity: 'common',
        energy: 0.5,
        cooldown: 29.93,
        description: 'A solar array patched into the frontier grids. Risk profile: medium.',
        flavor: 'Solar Array hums with a steady tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_197',
        name: 'Transit Gate',
        category: 'entertainment',
        rarity: 'uncommon',
        energy: 0.84,
        cooldown: 33.67,
        description: 'A transit gate patched into the frontier grids. Risk profile: medium.',
        flavor: 'Transit Gate hums with a steady tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_198',
        name: 'Bio Pod',
        category: 'ancient',
        rarity: 'uncommon',
        energy: 1.78,
        cooldown: 34.45,
        description: 'A bio pod patched into the frontier grids. Risk profile: medium.',
        flavor: 'Bio Pod hums with a warm tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_199',
        name: 'Trade Kiosk',
        category: 'decor',
        rarity: 'legendary',
        energy: 0.44,
        cooldown: 17.04,
        description: 'A trade kiosk patched into the frontier grids. Risk profile: low.',
        flavor: 'Trade Kiosk hums with a cold tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage', 'siphon'],
    },
    {
        id: 'obj_200',
        name: 'Arc Lamp',
        category: 'ancient',
        rarity: 'common',
        energy: 0.6,
        cooldown: 32.86,
        description: 'A arc lamp patched into the frontier grids. Risk profile: medium.',
        flavor: 'Arc Lamp hums with a cold tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_201',
        name: 'Cryo Tube',
        category: 'decor',
        rarity: 'uncommon',
        energy: 0.88,
        cooldown: 36.17,
        description: 'A cryo tube patched into the frontier grids. Risk profile: high.',
        flavor: 'Cryo Tube hums with a erratic tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_202',
        name: 'Refinery Valve',
        category: 'decor',
        rarity: 'epic',
        energy: 0.41,
        cooldown: 7.01,
        description: 'A refinery valve patched into the frontier grids. Risk profile: low.',
        flavor: 'Refinery Valve hums with a erratic tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage', 'siphon'],
    },
    {
        id: 'obj_203',
        name: 'Pulse Node',
        category: 'decor',
        rarity: 'uncommon',
        energy: 2.07,
        cooldown: 28.56,
        description: 'A pulse node patched into the frontier grids. Risk profile: low.',
        flavor: 'Pulse Node hums with a steady tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_204',
        name: 'Power Junction',
        category: 'utility',
        rarity: 'common',
        energy: 2.67,
        cooldown: 30.85,
        description: 'A power junction patched into the frontier grids. Risk profile: high.',
        flavor: 'Power Junction hums with a erratic tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_205',
        name: 'Hack Node',
        category: 'decor',
        rarity: 'rare',
        energy: 0.91,
        cooldown: 37.8,
        description: 'A hack node patched into the frontier grids. Risk profile: high.',
        flavor: 'Hack Node hums with a warm tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_206',
        name: 'Navigation Buoy',
        category: 'ancient',
        rarity: 'rare',
        energy: 0.85,
        cooldown: 48.07,
        description: 'A navigation buoy patched into the frontier grids. Risk profile: low.',
        flavor: 'Navigation Buoy hums with a whispering tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_207',
        name: 'Forge Crucible',
        category: 'security',
        rarity: 'uncommon',
        energy: 0.78,
        cooldown: 47.92,
        description: 'A forge crucible patched into the frontier grids. Risk profile: medium.',
        flavor: 'Forge Crucible hums with a cold tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_208',
        name: 'Scavenger Cache',
        category: 'security',
        rarity: 'common',
        energy: 0.79,
        cooldown: 38.53,
        description: 'A scavenger cache patched into the frontier grids. Risk profile: high.',
        flavor: 'Scavenger Cache hums with a warm tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_209',
        name: 'Wind Turbine',
        category: 'entertainment',
        rarity: 'uncommon',
        energy: 1.71,
        cooldown: 37.29,
        description: 'A wind turbine patched into the frontier grids. Risk profile: high.',
        flavor: 'Wind Turbine hums with a whispering tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_210',
        name: 'Bioforge Pod',
        category: 'research',
        rarity: 'common',
        energy: 2.73,
        cooldown: 23.07,
        description: 'A bioforge pod patched into the frontier grids. Risk profile: medium.',
        flavor: 'Bioforge Pod hums with a warm tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_211',
        name: 'Atlas Monolith',
        category: 'entertainment',
        rarity: 'uncommon',
        energy: 2.29,
        cooldown: 37.94,
        description: 'A atlas monolith patched into the frontier grids. Risk profile: medium.',
        flavor: 'Atlas Monolith hums with a whispering tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_212',
        name: 'Refinery Valve',
        category: 'ancient',
        rarity: 'uncommon',
        energy: 0.39,
        cooldown: 25.91,
        description: 'A refinery valve patched into the frontier grids. Risk profile: medium.',
        flavor: 'Refinery Valve hums with a warm tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_213',
        name: 'Bioforge Pod',
        category: 'security',
        rarity: 'uncommon',
        energy: 1.57,
        cooldown: 30.99,
        description: 'A bioforge pod patched into the frontier grids. Risk profile: high.',
        flavor: 'Bioforge Pod hums with a warm tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_214',
        name: 'Comms Uplink',
        category: 'research',
        rarity: 'uncommon',
        energy: 1.1,
        cooldown: 31.68,
        description: 'A comms uplink patched into the frontier grids. Risk profile: low.',
        flavor: 'Comms Uplink hums with a warm tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_215',
        name: 'Comms Uplink',
        category: 'security',
        rarity: 'rare',
        energy: 2.39,
        cooldown: 59.05,
        description: 'A comms uplink patched into the frontier grids. Risk profile: low.',
        flavor: 'Comms Uplink hums with a whispering tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_216',
        name: 'Bioforge Pod',
        category: 'manufacturing',
        rarity: 'common',
        energy: 2.07,
        cooldown: 59.51,
        description: 'A bioforge pod patched into the frontier grids. Risk profile: high.',
        flavor: 'Bioforge Pod hums with a whispering tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_217',
        name: 'Cargo Pallet',
        category: 'manufacturing',
        rarity: 'common',
        energy: 2.59,
        cooldown: 26.92,
        description: 'A cargo pallet patched into the frontier grids. Risk profile: medium.',
        flavor: 'Cargo Pallet hums with a whispering tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_218',
        name: 'Loot Chest',
        category: 'utility',
        rarity: 'common',
        energy: 0.54,
        cooldown: 42.63,
        description: 'A loot chest patched into the frontier grids. Risk profile: medium.',
        flavor: 'Loot Chest hums with a erratic tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_219',
        name: 'Med Drone Bay',
        category: 'research',
        rarity: 'epic',
        energy: 1.13,
        cooldown: 37.47,
        description: 'A med drone bay patched into the frontier grids. Risk profile: low.',
        flavor: 'Med Drone Bay hums with a erratic tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage', 'siphon'],
    },
    {
        id: 'obj_220',
        name: 'Drone Dock',
        category: 'decor',
        rarity: 'common',
        energy: 2.07,
        cooldown: 10.57,
        description: 'A drone dock patched into the frontier grids. Risk profile: high.',
        flavor: 'Drone Dock hums with a steady tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_221',
        name: 'Bioforge Pod',
        category: 'utility',
        rarity: 'rare',
        energy: 1.98,
        cooldown: 50.76,
        description: 'A bioforge pod patched into the frontier grids. Risk profile: high.',
        flavor: 'Bioforge Pod hums with a whispering tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_222',
        name: 'Hack Node',
        category: 'decor',
        rarity: 'uncommon',
        energy: 0.35,
        cooldown: 22.68,
        description: 'A hack node patched into the frontier grids. Risk profile: low.',
        flavor: 'Hack Node hums with a erratic tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_223',
        name: 'Hydro Tap',
        category: 'entertainment',
        rarity: 'common',
        energy: 2.8,
        cooldown: 14.37,
        description: 'A hydro tap patched into the frontier grids. Risk profile: medium.',
        flavor: 'Hydro Tap hums with a warm tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_224',
        name: 'Holo Projector',
        category: 'transport',
        rarity: 'rare',
        energy: 2.51,
        cooldown: 8.04,
        description: 'A holo projector patched into the frontier grids. Risk profile: medium.',
        flavor: 'Holo Projector hums with a whispering tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_225',
        name: 'Cryo Tube',
        category: 'research',
        rarity: 'common',
        energy: 0.71,
        cooldown: 50.89,
        description: 'A cryo tube patched into the frontier grids. Risk profile: high.',
        flavor: 'Cryo Tube hums with a cold tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_226',
        name: 'Med Drone Bay',
        category: 'entertainment',
        rarity: 'common',
        energy: 1.21,
        cooldown: 44.86,
        description: 'A med drone bay patched into the frontier grids. Risk profile: medium.',
        flavor: 'Med Drone Bay hums with a whispering tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_227',
        name: 'Weapon Rack',
        category: 'entertainment',
        rarity: 'common',
        energy: 0.9,
        cooldown: 58.14,
        description: 'A weapon rack patched into the frontier grids. Risk profile: medium.',
        flavor: 'Weapon Rack hums with a cold tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_228',
        name: 'Shield Emitter',
        category: 'research',
        rarity: 'legendary',
        energy: 1.45,
        cooldown: 21.22,
        description: 'A shield emitter patched into the frontier grids. Risk profile: medium.',
        flavor: 'Shield Emitter hums with a whispering tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage', 'siphon'],
    },
    {
        id: 'obj_229',
        name: 'Stasis Anchor',
        category: 'decor',
        rarity: 'legendary',
        energy: 2.34,
        cooldown: 49.27,
        description: 'A stasis anchor patched into the frontier grids. Risk profile: low.',
        flavor: 'Stasis Anchor hums with a erratic tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage', 'siphon'],
    },
    {
        id: 'obj_230',
        name: 'Loot Chest',
        category: 'entertainment',
        rarity: 'epic',
        energy: 1.69,
        cooldown: 11.54,
        description: 'A loot chest patched into the frontier grids. Risk profile: high.',
        flavor: 'Loot Chest hums with a warm tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage', 'siphon'],
    },
    {
        id: 'obj_231',
        name: 'Weapon Rack',
        category: 'security',
        rarity: 'rare',
        energy: 0.98,
        cooldown: 54.89,
        description: 'A weapon rack patched into the frontier grids. Risk profile: low.',
        flavor: 'Weapon Rack hums with a steady tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_232',
        name: 'Hack Node',
        category: 'resource',
        rarity: 'rare',
        energy: 2.51,
        cooldown: 56.25,
        description: 'A hack node patched into the frontier grids. Risk profile: medium.',
        flavor: 'Hack Node hums with a warm tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_233',
        name: 'Navigation Buoy',
        category: 'transport',
        rarity: 'common',
        energy: 1.27,
        cooldown: 10.41,
        description: 'A navigation buoy patched into the frontier grids. Risk profile: low.',
        flavor: 'Navigation Buoy hums with a warm tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_234',
        name: 'Circuit Relay',
        category: 'security',
        rarity: 'rare',
        energy: 1.92,
        cooldown: 48.73,
        description: 'A circuit relay patched into the frontier grids. Risk profile: low.',
        flavor: 'Circuit Relay hums with a warm tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_235',
        name: 'Weapon Rack',
        category: 'entertainment',
        rarity: 'uncommon',
        energy: 0.65,
        cooldown: 44.1,
        description: 'A weapon rack patched into the frontier grids. Risk profile: medium.',
        flavor: 'Weapon Rack hums with a whispering tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_236',
        name: 'Data Terminal',
        category: 'security',
        rarity: 'common',
        energy: 0.84,
        cooldown: 14.07,
        description: 'A data terminal patched into the frontier grids. Risk profile: high.',
        flavor: 'Data Terminal hums with a whispering tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_237',
        name: 'Stasis Anchor',
        category: 'decor',
        rarity: 'common',
        energy: 1.02,
        cooldown: 22.26,
        description: 'A stasis anchor patched into the frontier grids. Risk profile: low.',
        flavor: 'Stasis Anchor hums with a cold tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_238',
        name: 'Weather Node',
        category: 'research',
        rarity: 'uncommon',
        energy: 0.58,
        cooldown: 54.88,
        description: 'A weather node patched into the frontier grids. Risk profile: high.',
        flavor: 'Weather Node hums with a whispering tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_239',
        name: 'Power Junction',
        category: 'transport',
        rarity: 'uncommon',
        energy: 2.1,
        cooldown: 21.73,
        description: 'A power junction patched into the frontier grids. Risk profile: low.',
        flavor: 'Power Junction hums with a whispering tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
    {
        id: 'obj_240',
        name: 'Sensor Mast',
        category: 'resource',
        rarity: 'uncommon',
        energy: 0.77,
        cooldown: 42.08,
        description: 'A sensor mast patched into the frontier grids. Risk profile: high.',
        flavor: 'Sensor Mast hums with a erratic tone.',
        actions: ['inspect', 'use', 'repair', 'hack', 'overcharge', 'salvage'],
    },
];
